- name: check for virsh
  command: which virsh
  register: virsh_check
  changed_when: false
  failed_when: false

- name: start default network
  shell: "virsh net-start default"
  when: virsh_check.rc == 0
  register: net_start
  failed_when: net_start.rc != 0 and 'already active' not in net_start.stderr
  changed_when: net_start.rc == 0

- name: autostart default network
  shell: "virsh net-autostart default"
  when: virsh_check.rc == 0


- name: Get all groups
  getent:
    database: group

- name: add user to libvirt
  user:
    name: user
    groups: "{{ ['libvirt', 'libvirt-qemu', 'kvm', 'input', 'disk'] | intersect(ansible_facts.getent_group.keys() | list) | join(',') }}"
    append: yes
