- name: configure flatpak
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: "{{ item.method }}"
  with_items:  "{{ (flatpak_remote | default([]) + flatpak_remote_extra | default([])) | union([]) }}"      
  when: flatpak_remote is defined   

- name: update flatpaks
  #become_user: user
  shell:
    cmd: flatpak update --noninteractive    
  when: required_packages_flatpak is defined   

- name: install flatpak
  become_user: user
  community.general.flatpak:
    name: "{{ item }}"
    method: system
    state: present
  with_items: "{{ (required_packages_flatpak | default([]) + required_packages_flatpak_extra | default([])) | union([]) }}"
  when: required_packages_flatpak is defined or required_packages_flatpak_extra is defined
  #ignore_errors: yes
