- name: Ensure ca-certificates directory exists
  file:
    path: /etc/ca-certificates/trust-source/anchors
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Public certs
  copy:
    src: durp.crt
    dest: /etc/ca-certificates/trust-source/anchors/durp.crt

- name: Trust certs (Fedora)
  command: update-ca-trust
  when: ansible_facts['os_family'] == "RedHat"

- name: Trust certs (Debian)
  command: update-ca-certificates
  when: ansible_facts['os_family'] == "Debian"
