onboarding = false
[ui]
show_agent_labels_on_pane_borders = true

[theme]
name = "catppuccin"
auto_switch = false

[keys]
prefix = "ctrl+space"
previous_tab = "prefix+ctrl+h"
next_tab = "prefix+ctrl+l"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
navigate_pane_left = "h"
navigate_pane_right = "l"
