- name: install apt
  include_tasks: "./scripts/install_apt.yml"

- name: install brew
  include_tasks: "./scripts/install_brew.yml"

- name: install pacman
  include_tasks: "./scripts/install_pacman.yml"

  #- name: install go
  #  include_tasks: "./scripts/install_go.yml"

- name: install go apps
  include_tasks: "./scripts/install_goapps.yml"

- name: install flatpak
  include_tasks: "./scripts/install_flatpak.yml"

- name: configure systemd
  include_tasks: "./scripts/configure_systemd.yml"

- name: configure groups
  include_tasks: "./scripts/configure_groups.yml"

- name: configure qemu
  include_tasks: "./scripts/configure_qemu.yml"

- name: configure bat
  include_tasks: "./scripts/configure_bat.yml"

- name: trust internal certs
  include_tasks: "./scripts/install_local_ca.yml"
