- name: install apt
  include_tasks: "./scripts/install_apt.yml"

- name: install flatpak
  include_tasks: "./scripts/install_flatpak.yml"

- name: install brew
  include_tasks: "./scripts/install_brew.yml"

- name: install pacman
  include_tasks: "./scripts/install_pacman.yml"

- name: install go apps
  include_tasks: "./scripts/install_goapps.yml"

- name: configure systemd
  include_tasks: "./scripts/configure_systemd.yml"
