- name: install apt
  include_tasks: "./scripts/install_apt.yml"

- name: install flatpak
  include_tasks: "./scripts/install_flatpak.yml"

- name: install brew
  include_tasks: "./scripts/install_brew.yml"
