{
  allowUnfree = true;
  packageOverrides = pkgs: with pkgs; {
    myPackages = pkgs.buildEnv {
      name = "tools";
      paths = [
        neovim
        go
        lazygit
        glab
        oh-my-posh
        fzf
        ripgrep
        rclone
        k9s
        eza
        zoxide
        bat
        opentofu
        vivid
        stow
        bitwarden-cli
        wofi
        nmap
        kubectl
        podman
        podman-compose
        podman-desktop
        htop
        gimp
        yazi
        powershell
        devpod
        nerd-fonts.go-mono
        libsecret
        zenity
        libnotify
        wl-clipboard
        dnsutils
        golangci-lint
        caffeine-ng
        fastfetch
        timeshift
        sqlite
        btop
        argocd
        nodejs_24
        minio
        hugo
        minikube
        yq-go
        jq
        #swaynotificationcenter
        #grim
        #slurp
        #waybar
        talosctl
        awscli
        vault
      ];
    };
  };
}
