- name: Configure Security Auto Updates
  shell:
    cmd: dpkg-reconfigure -p medium unattended-upgrades
  become: yes
  when: ansible_facts["os_family"] == 'Debian'

- name: Configure dnf5 automatic
  include_tasks: "./scripts/configure_dnf5_automatic.yml"
  when: ansible_facts["os_family"] == 'RedHat'

- name: Check if UFW is installed
  ansible.builtin.command:
    cmd: ufw version
  register: ufw_version
  failed_when: false
  changed_when: false

- name: Configure UFW
  shell:
    cmd: |
      ufw enable
      ufw default deny incoming
      ufw default allow outgoing
  become: yes
  when: ufw_version.rc == 0

- name: Install and enable SSH server
  include_tasks: "./scripts/install_ssh.yml"
  when: ssh_server | bool

- name: Configure SSH
  include_tasks: "./scripts/configure_ssh.yml"
  when: ssh_server | bool

- name: Configure firewall ports
  include_tasks: "./scripts/configure_firewall.yml"
