install_homebrew_if_missing: false

#required_packages_brew:
#  - zsh-autosuggestions
#  - zsh-history-substring-search
#  - oh-my-posh

required_packages_dnf:
  - stow
  - zsh
  - kitty
  - qemu-kvm
  - qemu-system-x86
  - qemu-utils
  - libvirt-daemon
  - virt-manager
  - pcscd
  - pcsclite-devel
  - libfido2
  - libfido2-devel
  - yubikey-manager
  - yubikey-personalization
  - unattended-upgrades
  - btrfs-progs
  - steam
  - x11-apps
  - uidmap
  - make
  - gcc
  - zlib-devel
  - graphviz

  # sway
  - sway
  - waybar
  - wofi
  - swaybg
  - swayidle
  - swaylock
  - swayimg
  - wl-clipboard
  - grim
  - slurp
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk
  - pavucontrol
  - blueman
  - kanshi
  - wlogout
  - swaync
  - brightnessctl

  # core tools
  - neovim
  - tmux
  - fzf
  - zoxide
  - lazygit
  - eza
  - bat
  - wget
  - curl
  - nmap
  - kubectl
  - podman
  - podman-compose
  - helm
  - ripgrep
  - yq
  - jq
  - k9s
  - htop
  - yazi
  - gimp
  - file-roller
  - nautilus
  - remmina
  - freerdp
  - traceroute
  - dnsutils
  - smbclient
  - gvfs-smb
  - gvfs
  - bluez
  - bluez-utils
  - network-manager-applet
  - openssh
  - tlp
  - powertop

  # fonts
  - google-noto-sans-fonts
  - google-noto-serif-fonts
  - google-noto-mono-fonts

  # development
  - golang
  - nodejs
  - npm
  - python3
  - python3-pip
  - git

  # system
  - ufw
  - cronie
  - polkit
  - xsettingsd
  - flatpak
  - gnome-calculator
  - gnome-disk-utility

flatpak_remote:
  - {
      name: "flathub",
      url: "https://dl.flathub.org/repo/flathub.flatpakrepo",
      method: "user",
    }

required_packages_flatpak:
  - me.proton.Mail
  - com.protonvpn.www
  - org.remmina.Remmina
  - com.github.tchx84.Flatseal
  - com.vscodium.codium
  - org.chromium.Chromium
  - com.parsecgaming.parsec
  - org.videolan.VLC
  - fr.handbrake.ghb
  - com.spotify.Client
  - org.signal.Signal
  - com.yubico.yubioath
  - io.gitlab.librewolf-community
  - com.brave.Browser
  - com.moonlight_stream.Moonlight
  - com.discordapp.Discord
  - com.super_productivity.SuperProductivity
  - md.obsidian.Obsidian
  - org.inkscape.Inkscape

go_apps:
  - github.com/charmbracelet/vhs@latest
  - github.com/charmbracelet/glow@latest
  - github.com/swaggo/swag/cmd/swag@latest
  - github.com/air-verse/air@latest
  - github.com/sqlc-dev/sqlc/cmd/sqlc@latest
  - github.com/pressly/goose/v3/cmd/goose@latest
  - github.com/testcontainers/testcontainers-go

systemd_service:
  - libvirtd.service
  - pcscd.service
  - ufw.service
  - podman.socket
  - cronie.service

user_groups:
  - video
  - sudo
  - libvirt
  - ykusers
