install_homebrew_if_missing: true

required_packages_brew:
  - lazygit
  - fzf
  - glab
  - go
  - neovim
  - oh-my-posh
  - tpm
  - terraform
  - kubernetes-cli
  - zsh-autosuggestions
  - bitwarden-cli
  - hashicorp/tap/vault
  - ffmpeg
  - ttyd
  - bat
  - eza
  - fastfetch
  - vivid
  - yazi

apt_keys:
  - https://packages.microsoft.com/keys/microsoft.asc
apt_repo:
  - deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main

required_packages_apt:
  - powershell
  - curl
  - wofi
  - swaybg
  - swayidle
  - swaylock
  - swayimg
  - kanshi
  - waybar
  #- sway-notification-center
  - grim
  - slurp
  - openresolv
  - podman
  - brightnessctl
  - pavucontrol
  - kitty

flatpak_remote:
  - {name: 'flathub', url: "https://dl.flathub.org/repo/flathub.flatpakrepo"}

required_packages_flatpak:
  - VSCodium

